name: Build

on: [push, pull_request]
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # install deps
      #- name: Update System
      #  run: sudo apt-get update && sudo apt-get upgrade -yq
      - name: Download and Extract BOOST v1.73
        shell: bash
        run: |
          curl -s https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2
          tar --bzip2 -xf ${{runner.workspace}}/boost_1_73_0.tar.bz2
      - name: Build and Install BOOST v1.73
        shell: bash
        working-directory: ${{runner.workspace}}/boost_1_73_0
        run: |
          ./bootstrap.sh --prefix=$GITHUB_WORKSPACE/external --with-libraries=system,filesystem,unit_test_framework
          ./b2 install

      # build project
      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build
      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE
      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -C $BUILD_TYPE
        