name: Build

on: [push, pull_request]
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # install deps
      #- name: Update System
      #  run: sudo apt-get update && sudo apt-get upgrade -yq
      - name: Download and Extract BOOST v1.74
        shell: bash
        run: |
          # I have been trolled by CDN redirection for hours... Wow!
          curl -L https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.gz --output ${{runner.workspace}}/boost_1_74_0.tar.gz -s
          tar -xzvf ${{runner.workspace}}/boost_1_74_0.tar.gz
      - name: Build and Install BOOST v1.74
        shell: bash
        working-directory: ${{runner.workspace}}/boost_1_74_0
        run: |
          ${{runner.workspace}}/boost_1_74_0/bootstrap.sh --prefix=$GITHUB_WORKSPACE/external --with-libraries=system,filesystem,unit_test_framework
          ${{runner.workspace}}/boost_1_74_0/b2 install

      # build project
      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build
      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE
      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -C $BUILD_TYPE
        